language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nosetests  --with-coverage --cover-package=pymongo-schema
after_success:
  - coveralls