language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
services:
  - mongodb
before_script:
  - sleep 5  # wait for mongoDB to accept connections
  - mongo mydb_test --eval 'db.test_col.insert({"test_field":"test_value"});'
script:
  - python setup.py install
  - nosetests  --with-coverage
after_success:
  - coveralls